# https://grafana.com/docs/grafana/latest/datasources/prometheus/#provisioning-example
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  # Access mode - proxy (server in the UI) or direct (browser in the UI).
  url: http://prometheus:9090
  editable: true
  jsonData:
    httpMethod: POST
    manageAlerts: false
    prometheusType: Prometheus
    prometheusVersion: 2.54.1
    cacheLevel: 'High'
    disableRecordingRules: false
    incrementalQueryOverlapWindow: 10m
