# https://github.com/guessi/docker-compose-etcd/blob/master/docker-compose.yml

x-variables:
  flag_initial_cluster_token: &flag_initial_cluster_token '--initial-cluster-token=mys3cr3ttok3n'
  common_settings: &common_settings
    image: quay.io/coreos/etcd:v3.5.15
    entrypoint: /usr/local/bin/etcd

networks:
  etcd:
    name: etcd
    driver: bridge

services:
  etcd-1:
    <<: *common_settings
    container_name: etcd-1
    networks:
      - etcd
    command:
      - '--name=etcd-1'
      - '--initial-advertise-peer-urls=http://etcd-1:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-1:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
      - '--data-dir=/etcd_data'
      - *flag_initial_cluster_token
    volumes:
      - etcd1:/etcd_data
    ports:
      - 2379:2379
  
  etcd-2:
    <<: *common_settings
    container_name: etcd-2
    networks:
      - etcd
    command:
      - '--name=etcd-2'
      - '--initial-advertise-peer-urls=http://etcd-2:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-2:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
      - '--data-dir=/etcd_data'
      - *flag_initial_cluster_token
    volumes:
      - etcd2:/etcd_data
    ports:
      - 2380:2379
  
  etcd-3:
    <<: *common_settings
    container_name: etcd-3
    networks:
      - etcd
    command:
      - '--name=etcd-3'
      - '--initial-advertise-peer-urls=http://etcd-3:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-3:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd-1:2380,etcd-2=http://etcd-2:2380,etcd-3=http://etcd-3:2380'
      - '--initial-cluster-state=new'
      - '--data-dir=/etcd_data'
      - *flag_initial_cluster_token
    volumes:
      - etcd3:/etcd_data
    ports:
      - 2381:2379

volumes:
  etcd1:
    name: etcd1
    driver: local
    driver_opts:
      type: none
      o: bind
      device: etcd1
  etcd2:
    name: etcd2
    driver: local
    driver_opts:
      type: none
      o: bind
      device: etcd2
  etcd3:
    name: etcd3
    driver: local
    driver_opts:
      type: none
      o: bind
      device: etcd3
