# https://github.com/jpetazzo/container.training/blob/main/compose/simple-k8s-control-plane/docker-compose.yaml

version: "3"

networks:
  etcd:
    name: etcd
    external: true

services:

  # https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/units/kube-apiserver.service
  kube-apiserver:
    container_name: kube-apiserver
    networks:
      - etcd
    image: registry.k8s.io/kube-apiserver:v1.31.0
    entrypoint: kube-apiserver
    command: 
      - --bind-address=0.0.0.0
      - --client-ca-file=/var/lib/kubernetes/ca.crt
      - --etcd-servers=http://etcd-1:2379,http://etcd-2:2379,http://etcd-3:2379 
      - --encryption-provider-config=/var/lib/kubernetes/encryption-config.yaml
      - --kubelet-certificate-authority=/var/lib/kubernetes/ca.crt
      - --kubelet-client-key=/var/lib/kubernetes/kube-api-server.key
      - --kubelet-client-certificate=/var/lib/kubernetes/kube-api-server.crt
      - --service-account-key-file=/var/lib/kubernetes/service-accounts.crt
      - --service-account-signing-key-file=/var/lib/kubernetes/service-accounts.key
      - --service-account-issuer=https://kube-apiserver:6443
      - --service-cluster-ip-range=10.0.0.0/24
      - --service-node-port-range=30000-32767
      - --tls-cert-file=/var/lib/kubernetes/kube-api-server.crt
      - --tls-private-key-file=/var/lib/kubernetes/kube-api-server.key
    volumes:
      - apiserver:/var/lib/kubernetes/
    ports:
      - 6443:6443

  kube-controller-manager:
    container_name: kube-controller-manager
    networks:
      - etcd
    image: registry.k8s.io/kube-controller-manager:v1.31.0
    entrypoint: kube-controller-manager
    command:
      - --cluster-cidr=10.200.0.0/16
      - --cluster-name=kubernetes
      - --cluster-signing-cert-file=/var/lib/kubernetes/ca.crt
      - --cluster-signing-key-file=/var/lib/kubernetes/ca.key
      - --kubeconfig=/var/lib/kubernetes/kube-controller-manager.kubeconfig
      - --root-ca-file=/var/lib/kubernetes/ca.crt
      - --service-account-private-key-file=/var/lib/kubernetes/service-accounts.key
      - --service-cluster-ip-range=10.0.0.0/24
      - --use-service-account-credentials=true
      #- --tls-cert-file=/var/lib/kubernetes/ca.crt
      #- --tls-private-key-file=/var/lib/kubernetes/ca.key
    volumes:
      - controller-manager:/var/lib/kubernetes/
    
  kube-scheduler:
    container_name: kube-scheduler
    networks:
      - etcd
    image: registry.k8s.io/kube-scheduler:v1.31.0
    entrypoint: kube-scheduler
    command:
      - --config=/var/lib/kubernetes/kube-scheduler.yaml
    volumes:
      - scheduler:/var/lib/kubernetes/

  kubectl:
    container_name: kubectl
    networks:
      - etcd
    image: bitnami/kubectl:1.31.1-debian-12-r3
    entrypoint: sleep
    command:
      - '86400'
    volumes:
      - kubectl:/.kube/

volumes:
  apiserver:
    name: apiserver
    driver: local
    driver_opts:
      type: none
      o: bind
      device: apiserver
  controller-manager:
    name: controller-manager
    driver: local
    driver_opts:
      type: none
      o: bind
      device: controller-manager
  scheduler:
    name: scheduler
    driver: local
    driver_opts:
      type: none
      o: bind
      device: scheduler
  kubectl:
    name: kubectl
    driver: local
    driver_opts:
      type: none
      o: bind
      device: kubectl
